branches:
  - branch: 2.1.0-sp
    bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 3.1.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 3.2.x
bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
